---
application-auto-scaling_DescribeScheduledActions:
  title: Use Get-AASScheduledAction
  title_abbrev: Get-AASScheduledAction
  synopsis: use Get-AASScheduledAction
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Get-AASScheduledAction
        excerpts:
        - snippet_files: []
          description: "<emphasis role=\"bold\">Example 1: This cmdlet lists the actions scheduled for your Auto Scaling group that haven't run or that have not reached their end time. </emphasis>"
        - snippet_files:
          - .doc_gen/snippet_files/application-autoscaling_Get-AASScheduledAction.1.1.ps1
          description:
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: |-
            <programlisting language="none" role="nocopy">CreationTime         : 12/22/2019 9:25:52 AM
            EndTime              : 1/1/0001 12:00:00 AM
            ResourceId           : fleet/MyFleet
            ScalableDimension    : appstream:fleet:DesiredCapacity
            ScalableTargetAction : Amazon.ApplicationAutoScaling.Model.ScalableTargetAction
            Schedule             : cron(0 0 8 ? * MON-FRI *)
            ScheduledActionARN   : arn:aws:autoscaling:us-west-2:012345678912:scheduledAction:4897ca24-3caa-4bf1-8484-851a089b243c:resource/appstream/fleet/MyFleet:scheduledActionName
                                   /WeekDaysFleetScaling
            ScheduledActionName  : WeekDaysFleetScaling
            ServiceNamespace     : appstream
            StartTime            : 1/1/0001 12:00:00 AM</programlisting>
  services:
    application-auto-scaling:
      DescribeScheduledActions:

