---
appstream_DeleteDirectoryConfig:
  title: Use Remove-APSDirectoryConfig
  title_abbrev: Remove-APSDirectoryConfig
  synopsis: use Remove-APSDirectoryConfig
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Remove-APSDirectoryConfig
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This sample removes AppStream Directory configuration</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/appstream_Remove-APSDirectoryConfig.1.1.ps1
          description:
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: |-
            <programlisting language="none" role="nocopy">Confirm
            Are you sure you want to perform this action?
            Performing the operation "Remove-APSDirectoryConfig (DeleteDirectoryConfig)" on target "contoso.com".
            [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A</programlisting>
  services:
    appstream:
      DeleteDirectoryConfig:

