---
auto-scaling_PutNotificationConfiguration:
  title: Use Write-ASNotificationConfiguration
  title_abbrev: Write-ASNotificationConfiguration
  synopsis: use Write-ASNotificationConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Write-ASNotificationConfiguration
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example configures the specified Auto Scaling group to send a notification to the specified SNS topic when it launches EC2 instances.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/auto-scaling_Write-ASNotificationConfiguration.1.1.ps1
        - description: '<emphasis role="bold">Example 2: This example configures the specified Auto Scaling group to send a notification to the specified SNS topic when it launches or terminates EC2 instances.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/auto-scaling_Write-ASNotificationConfiguration.2.1.ps1
  services:
    auto-scaling:
      PutNotificationConfiguration:


