---
auto-scaling_CreateLaunchConfiguration:
  title: Use New-ASLaunchConfiguration
  title_abbrev: New-ASLaunchConfiguration
  synopsis: use New-ASLaunchConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: New-ASLaunchConfiguration
        excerpts:
        - description: "<emphasis role=\"bold\">Example 1: This example creates a launch configuration named 'my-lc'. The EC2 instances launched by Auto Scaling groups that use this launch configuration use specified instance type, AMI, security group, and IAM role.</emphasis>"
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/auto-scaling_New-ASLaunchConfiguration.1.1.ps1
  services:
    auto-scaling:
      CreateLaunchConfiguration:


