---
codedeploy_ListDeployments:
  title: Use Get-CDDeploymentList
  title_abbrev: Get-CDDeploymentList
  synopsis: use Get-CDDeploymentList
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Get-CDDeploymentList
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example gets a list of deployment IDs for the specified application and deployment group.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Get-CDDeploymentList.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">d-QZMRGSTEX
            d-RR0T5KTEX</programlisting>
          snippet_files: []
  services:
    codedeploy:
      ListDeployments:

