---
codedeploy_BatchGetApplications:
  title: Use Get-CDApplicationBatch
  title_abbrev: Get-CDApplicationBatch
  synopsis: use Get-CDApplicationBatch
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Get-CDApplicationBatch
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example gets information about the specified applications.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Get-CDApplicationBatch.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ApplicationId                           ApplicationName              CreateTime              LinkedToGitHub
            -------------                           ---------------              ----------              --------------
            e07fb938-091e-4f2f-8963-4d3e8EXAMPLE    CodeDeployDemoApplication    7/20/2015 9:49:48 PM    False
            1ecfd602-62f1-4038-8f0d-06688EXAMPLE    CodePipelineDemoApplication  8/13/2015 5:53:26 PM    False</programlisting>
          snippet_files: []
  services:
    codedeploy:
      BatchGetApplications:

