---
codedeploy_ListDeploymentInstances:
  title: Use Get-CDDeploymentInstanceList
  title_abbrev: Get-CDDeploymentInstanceList
  synopsis: use Get-CDDeploymentInstanceList
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Get-CDDeploymentInstanceList
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example gets a list of instance IDs for the specified deployment.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Get-CDDeploymentInstanceList.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">i-254e22EX
            i-274e22EX
            i-3b4e22EX</programlisting>
          snippet_files: []
  services:
    codedeploy:
      ListDeploymentInstances:

