---
config-service_ListTagsForResource:
  title: Use Get-CFGResourceTag
  title_abbrev: Get-CFGResourceTag
  synopsis: use Get-CFGResourceTag
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Get-CFGResourceTag
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example lists associated tags for the given resource</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/config-service_Get-CFGResourceTag.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">Key     Value
            ---     -----
            Version 1.3</programlisting>
          snippet_files: []
  services:
    config-service:
      ListTagsForResource:


