---
lambda_PutProvisionedConcurrencyConfig:
  title: Use Write-LMProvisionedConcurrencyConfig
  title_abbrev: Write-LMProvisionedConcurrencyConfig
  synopsis: use Write-LMProvisionedConcurrencyConfig
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Write-LMProvisionedConcurrencyConfig
        excerpts:
        - snippet_files: []
          description: "<emphasis role=\"bold\">Example 1: This example adds a provisioned concurrency configuration to a Function's Alias</emphasis>"
        - snippet_files:
          - .doc_gen/snippet_files/lambda_Write-LMProvisionedConcurrencyConfig.1.1.ps1
          description:
  services:
    lambda:
      PutProvisionedConcurrencyConfig:

