---
route-53_CreateQueryLoggingConfig:
  title: Use New-R53QueryLoggingConfig
  title_abbrev: New-R53QueryLoggingConfig
  synopsis: use New-R53QueryLoggingConfig
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: New-R53QueryLoggingConfig
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This example creates a new Route53 DNS query logging configuration for the specified hosted zone. Amazon Route53 will publish DNS query logs to the specified Cloudwatch log group.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/route-53_New-R53QueryLoggingConfig.1.1.ps1
          description:
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: |-
            <programlisting language="none" role="nocopy">QueryLoggingConfig                      Location
            ------------------                      --------
            Amazon.Route53.Model.QueryLoggingConfig https://route53.amazonaws.com/2013-04-01/queryloggingconfig/ee5aaa95-4e03-4fdc-9d28-9e24ddaaaaa3</programlisting>
  services:
    route-53:
      CreateQueryLoggingConfig:


