---
s3_GetBucketMetricsConfiguration:
  title: Use Get-S3BucketMetricsConfiguration
  title_abbrev: Get-S3BucketMetricsConfiguration
  synopsis: use Get-S3BucketMetricsConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Get-S3BucketMetricsConfiguration
        excerpts:
        - snippet_files: []
          description: "<emphasis role=\"bold\">Example 1: This command returns the details about the metrics filter named 'testfilter' for the given S3 bucket.</emphasis>"
        - snippet_files:
          - .doc_gen/snippet_files/s3_Get-S3BucketMetricsConfiguration.1.1.ps1
          description:
  services:
    s3:
      GetBucketMetricsConfiguration:

