---
s3_ListBucketAnalyticsConfigurations:
  title: Use Get-S3BucketAnalyticsConfigurationList
  title_abbrev: Get-S3BucketAnalyticsConfigurationList
  synopsis: use Get-S3BucketAnalyticsConfigurationList
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Get-S3BucketAnalyticsConfigurationList
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This command returns the first 100 analytics configurations of the given S3 bucket.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/s3_Get-S3BucketAnalyticsConfigurationList.1.1.ps1
          description:
  services:
    s3:
      ListBucketAnalyticsConfigurations:

