---
s3_DeleteCORSConfiguration:
  title: Use Remove-S3CORSConfiguration
  title_abbrev: Remove-S3CORSConfiguration
  synopsis: use Remove-S3CORSConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Remove-S3CORSConfiguration
        excerpts:
        - description: '<emphasis role="bold">Example 1: This command removes the CORS configuration for the given S3 bucket.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/s3_Remove-S3CORSConfiguration.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">Confirm
            Are you sure you want to perform this action?
            Performing the operation "Remove-S3CORSConfiguration (DeleteCORSConfiguration)" on target "amzn-s3-demo-bucket".
            [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y</programlisting>
          snippet_files: []
  services:
    s3:
      DeleteCORSConfiguration:

