---
s3_DeleteBucketAnalyticsConfiguration:
  title: Use Remove-S3BucketAnalyticsConfiguration
  title_abbrev: Remove-S3BucketAnalyticsConfiguration
  synopsis: use Remove-S3BucketAnalyticsConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Remove-S3BucketAnalyticsConfiguration
        excerpts:
        - description: "<emphasis role=\"bold\">Example 1: The command removes the analytics filter with name 'testfilter' in the given S3 bucket.</emphasis>"
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/s3_Remove-S3BucketAnalyticsConfiguration.1.1.ps1
  services:
    s3:
      DeleteBucketAnalyticsConfiguration:

