---
s3_PutBucketAccelerateConfiguration:
  title: Use Write-S3BucketAccelerateConfiguration
  title_abbrev: Write-S3BucketAccelerateConfiguration
  synopsis: use Write-S3BucketAccelerateConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Write-S3BucketAccelerateConfiguration
        excerpts:
        - description: '<emphasis role="bold">Example 1: This command enables the transfer acceleration for the given S3 bucket.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/s3_Write-S3BucketAccelerateConfiguration.1.1.ps1
  services:
    s3:
      PutBucketAccelerateConfiguration:

