---
s3_PutLifecycleConfiguration:
  title: Use Write-S3LifecycleConfiguration
  title_abbrev: Write-S3LifecycleConfiguration
  synopsis: use Write-S3LifecycleConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Write-S3LifecycleConfiguration
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example writes / replaces the configuration provided in the $NewRule. This configuration is making sure to limit the scope objects with given prefix and tag values.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/s3_Write-S3LifecycleConfiguration.1.1.ps1
        - description: "<emphasis role=\"bold\">Example 2: This example sets multiple rules with filtering. $ArchiveRule sets the objects to archive in 30 days to Glacier and 120 to DeepArchive. $ExpireRule expires both current and previous versions in 150 days for objects with 'py' prefix and tag:key 'archieved' set to 'yes'.</emphasis>"
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/s3_Write-S3LifecycleConfiguration.2.1.ps1
  services:
    s3:
      PutLifecycleConfiguration:

